/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:window1:754091:
  appc.background(230);
} //_CODE_:window1:754091:

public void slider1(GSlider source, GEvent event) { //_CODE_:startPositionX:477372:
  cannon.x = startPositionX.getValueI();
} //_CODE_:startPositionX:477372:

public void slider2_change1(GSlider source, GEvent event) { //_CODE_:startPositionY:305206:
  cannon.y = startPositionY.getValueI();
} //_CODE_:startPositionY:305206:

public void slider2_change2(GSlider source, GEvent event) { //_CODE_:endPositionX:366247:
  target.x = endPositionX.getValueI();
} //_CODE_:endPositionX:366247:

public void slider2_change3(GSlider source, GEvent event) { //_CODE_:endPositionY:629114:
  target.y = endPositionY.getValueI() - 5;
} //_CODE_:endPositionY:629114:

public void slider2_theta(GSlider source, GEvent event) { //_CODE_:thetaSlider:880993:
  theta = thetaSlider.getValueI();
} //_CODE_:thetaSlider:880993:

public void slider2_change4(GSlider source, GEvent event) { //_CODE_:speedSlider:306060:
  initSpeed = speedSlider.getValueI();
} //_CODE_:speedSlider:306060:

public void button1_click1(GButton source, GEvent event) { //_CODE_:playButton:740675:
  myProjectile.resetStats();
  isRunning = true;
} //_CODE_:playButton:740675:

public void dropList1_click1(GDropList source, GEvent event) { //_CODE_:dropList1:259944:
  if(dropList1.getSelectedText().equals("Speed & Angle")) {
    mode = "speed and theta";
  }
  
  else if(dropList1.getSelectedText().equals("Angle")) {
    mode = "theta";
  }
    
} //_CODE_:dropList1:259944:

public void button1_click2(GButton source, GEvent event) { //_CODE_:demo1:607706:
  setDemoValues(1);
} //_CODE_:demo1:607706:

public void button1_click3(GButton source, GEvent event) { //_CODE_:demo2:422086:
  setDemoValues(2);
} //_CODE_:demo2:422086:

public void button1_click4(GButton source, GEvent event) { //_CODE_:demo4:319300:
  setDemoValues(4);
} //_CODE_:demo4:319300:

public void button1_click5(GButton source, GEvent event) { //_CODE_:demo5:653377:
  setDemoValues(5);
} //_CODE_:demo5:653377:

public void button1_click6(GButton source, GEvent event) { //_CODE_:demo3:804293:
  setDemoValues(3);
} //_CODE_:demo3:804293:

public void button1_click7(GButton source, GEvent event) { //_CODE_:demo6:764358:
  setDemoValues(6);
} //_CODE_:demo6:764358:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  window1 = GWindow.getWindow(this, "Window title", 0, 0, 450, 500, JAVA2D);
  window1.noLoop();
  window1.setActionOnClose(G4P.KEEP_OPEN);
  window1.addDrawHandler(this, "win_draw1");
  startPositionX = new GSlider(window1, 11, 54, 196, 40, 10.0);
  startPositionX.setShowValue(true);
  startPositionX.setShowLimits(true);
  startPositionX.setLimits(50, 0, 600);
  startPositionX.setNumberFormat(G4P.INTEGER, 0);
  startPositionX.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  startPositionX.setOpaque(false);
  startPositionX.addEventHandler(this, "slider1");
  label1 = new GLabel(window1, 56, 26, 97, 19);
  label1.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label1.setText("Start Position (X)");
  label1.setOpaque(false);
  label2 = new GLabel(window1, 59, 101, 97, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("Start Position (Y)");
  label2.setOpaque(false);
  startPositionY = new GSlider(window1, 9, 127, 198, 40, 10.0);
  startPositionY.setShowValue(true);
  startPositionY.setShowLimits(true);
  startPositionY.setLimits(300, 0, 600);
  startPositionY.setNumberFormat(G4P.INTEGER, 0);
  startPositionY.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  startPositionY.setOpaque(false);
  startPositionY.addEventHandler(this, "slider2_change1");
  label3 = new GLabel(window1, 280, 23, 100, 21);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText("End Position (X)");
  label3.setOpaque(false);
  label4 = new GLabel(window1, 281, 102, 101, 20);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText("End Position (Y)");
  label4.setOpaque(false);
  endPositionX = new GSlider(window1, 229, 53, 203, 40, 10.0);
  endPositionX.setShowValue(true);
  endPositionX.setShowLimits(true);
  endPositionX.setLimits(550, 0, 600);
  endPositionX.setNumberFormat(G4P.INTEGER, 0);
  endPositionX.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  endPositionX.setOpaque(false);
  endPositionX.addEventHandler(this, "slider2_change2");
  endPositionY = new GSlider(window1, 229, 128, 204, 40, 10.0);
  endPositionY.setShowValue(true);
  endPositionY.setShowLimits(true);
  endPositionY.setLimits(300, 0, 600);
  endPositionY.setNumberFormat(G4P.INTEGER, 0);
  endPositionY.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  endPositionY.setOpaque(false);
  endPositionY.addEventHandler(this, "slider2_change3");
  label5 = new GLabel(window1, 184, 241, 80, 23);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText("θ (angle)");
  label5.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  label5.setOpaque(false);
  thetaSlider = new GSlider(window1, 44, 270, 368, 40, 10.0);
  thetaSlider.setShowValue(true);
  thetaSlider.setShowLimits(true);
  thetaSlider.setLimits(45, 0, 359);
  thetaSlider.setNumberFormat(G4P.INTEGER, 0);
  thetaSlider.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  thetaSlider.setOpaque(false);
  thetaSlider.addEventHandler(this, "slider2_theta");
  speedSlider = new GSlider(window1, 43, 342, 369, 41, 10.0);
  speedSlider.setShowValue(true);
  speedSlider.setShowLimits(true);
  speedSlider.setLimits(30, 1, 150);
  speedSlider.setNumberFormat(G4P.INTEGER, 0);
  speedSlider.setOpaque(false);
  speedSlider.addEventHandler(this, "slider2_change4");
  playButton = new GButton(window1, 183, 465, 80, 30);
  playButton.setText("Play");
  playButton.setLocalColorScheme(GCScheme.GOLD_SCHEME);
  playButton.addEventHandler(this, "button1_click1");
  label6 = new GLabel(window1, 187, 314, 80, 29);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText("Initial Speed");
  label6.setOpaque(false);
  label7 = new GLabel(window1, 184, 186, 80, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("Input Type");
  label7.setOpaque(false);
  dropList1 = new GDropList(window1, 163, 209, 121, 80, 3, 10);
  dropList1.setItems(loadStrings("list_259944"), 0);
  dropList1.addEventHandler(this, "dropList1_click1");
  demo1 = new GButton(window1, 2, 416, 66, 33);
  demo1.setText("Demo 1");
  demo1.addEventHandler(this, "button1_click2");
  demo2 = new GButton(window1, 80, 416, 66, 33);
  demo2.setText("Demo 2");
  demo2.addEventHandler(this, "button1_click3");
  demo4 = new GButton(window1, 230, 416, 66, 33);
  demo4.setText("Demo 4");
  demo4.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  demo4.addEventHandler(this, "button1_click4");
  demo5 = new GButton(window1, 305, 416, 66, 33);
  demo5.setText("Demo 5");
  demo5.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  demo5.addEventHandler(this, "button1_click5");
  demo3 = new GButton(window1, 155, 416, 66, 33);
  demo3.setText("Demo 3");
  demo3.addEventHandler(this, "button1_click6");
  demo6 = new GButton(window1, 380, 416, 66, 33);
  demo6.setText("Demo 6");
  demo6.setLocalColorScheme(GCScheme.PURPLE_SCHEME);
  demo6.addEventHandler(this, "button1_click7");
  window1.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow window1;
GSlider startPositionX; 
GLabel label1; 
GLabel label2; 
GSlider startPositionY; 
GLabel label3; 
GLabel label4; 
GSlider endPositionX; 
GSlider endPositionY; 
GLabel label5; 
GSlider thetaSlider; 
GSlider speedSlider; 
GButton playButton; 
GLabel label6; 
GLabel label7; 
GDropList dropList1; 
GButton demo1; 
GButton demo2; 
GButton demo4; 
GButton demo5; 
GButton demo3; 
GButton demo6; 
